version: "2.2"
services:
  neo4j:
    image: neo4j
    ports:
      - "7687:7687"
      - "7474:7474"
    # volumes:
    #   - .:/var/lib/neo4j/import
  mongodb:
    image: mongo:latest
    environment:
      MONGO_INITDB_ROOT_USERNAME: root
      MONGO_INITDB_ROOT_PASSWORD: password
    ports:
      - 27017:27017
  spark-master:
    image: bitnami/spark:3
    container_name: spark-master
    environment:
      - SPARK_MODE=master
      - SPARK_MASTER_HOST=spark-master
      - SPARK_NO_DAEMONIZE=yes
    ports:
      - "8080:8080"
      - "7077:7077"

  spark-worker-1:
    image: bitnami/spark:3
    container_name: spark-worker-1
    environment:
      - SPARK_MODE=worker
      - SPARK_MASTER_URL=spark://spark-master:7077
      - SPARK_NO_DAEMONIZE=yes

  spark-worker-2:
    image: bitnami/spark:3
    container_name: spark-worker-2
    environment:
      - SPARK_MODE=worker
      - SPARK_MASTER_URL=spark://spark-master:7077
      - SPARK_NO_DAEMONIZE=yes
  pyspark:
    image: jupyter/pyspark-notebook
    ports:
      - "8888:8888"
    volumes:
      - ./jars:/jars
    environment:
      - SPARK_OPTS=--master=spark://spark-master:7077
      - PYSPARK_DRIVER_PYTHON_OPTS=notebook

# neo4j/'password'
#docker exec -it cpts415-mongodb-1 mongosh -u "root" -p "password"
#use mongo
#db.createCollection('paths')